export interface AnalysisQuestion {
  id: string
  text: string
  relatedProjects: string[]
  category: "Technical" | "Market" | "Financial" | "Impact" | "Implementation"
  tags: string[]
  createdAt: string
  updatedAt: string
  isRequired: boolean
}

export const analysisQuestionsData: AnalysisQuestion[] = [
  {
    id: "q-1",
    text: "What specific environmental problem does your solution address?",
    relatedProjects: ["EU Green Innovation Fund", "Circular Economy Fund"],
    category: "Impact",
    tags: ["Environment", "Problem Statement", "Impact"],
    createdAt: "2024-12-10",
    updatedAt: "2025-01-15",
    isRequired: true,
  },
  {
    id: "q-2",
    text: "How does your solution align with EU Green Deal objectives?",
    relatedProjects: ["EU Green Innovation Fund", "Renewable Energy Grant"],
    category: "Impact",
    tags: ["Policy Alignment", "EU Green Deal", "Compliance"],
    createdAt: "2024-12-12",
    updatedAt: "2025-01-15",
    isRequired: true,
  },
  {
    id: "q-3",
    text: "What is your competitive advantage compared to existing solutions?",
    relatedProjects: ["SME Growth Initiative", "Digital Europe Programme", "Health Innovation Programme"],
    category: "Market",
    tags: ["Competition", "Market Analysis", "Differentiation"],
    createdAt: "2024-12-15",
    updatedAt: "2025-01-20",
    isRequired: true,
  },
  {
    id: "q-4",
    text: "How will you ensure market adoption of your solution?",
    relatedProjects: ["SME Growth Initiative", "Digital Europe Programme"],
    category: "Market",
    tags: ["Go-to-Market", "Adoption", "Strategy"],
    createdAt: "2024-12-18",
    updatedAt: "2025-01-22",
    isRequired: false,
  },
  {
    id: "q-5",
    text: "What are the main technical risks and how will you mitigate them?",
    relatedProjects: ["Horizon Europe Research Grant", "Health Innovation Programme"],
    category: "Technical",
    tags: ["Risk Management", "Technical Challenges", "Mitigation"],
    createdAt: "2024-12-20",
    updatedAt: "2025-01-25",
    isRequired: true,
  },
  {
    id: "q-6",
    text: "Describe your revenue model and pricing strategy.",
    relatedProjects: ["SME Growth Initiative", "Digital Europe Programme"],
    category: "Financial",
    tags: ["Revenue", "Pricing", "Business Model"],
    createdAt: "2025-01-05",
    updatedAt: "2025-01-28",
    isRequired: false,
  },
  {
    id: "q-7",
    text: "What is the total addressable market for your solution?",
    relatedProjects: ["SME Growth Initiative", "Digital Europe Programme", "Health Innovation Programme"],
    category: "Market",
    tags: ["Market Size", "TAM", "Market Analysis"],
    createdAt: "2025-01-08",
    updatedAt: "2025-01-30",
    isRequired: true,
  },
  {
    id: "q-8",
    text: "How will you measure the environmental impact of your solution?",
    relatedProjects: ["EU Green Innovation Fund", "Circular Economy Fund", "Renewable Energy Grant"],
    category: "Impact",
    tags: ["Metrics", "Environmental Impact", "Measurement"],
    createdAt: "2025-01-10",
    updatedAt: "2025-02-01",
    isRequired: true,
  },
  {
    id: "q-9",
    text: "What is your implementation timeline and key milestones?",
    relatedProjects: [
      "EU Green Innovation Fund",
      "Horizon Europe Research Grant",
      "Digital Europe Programme",
      "Health Innovation Programme",
    ],
    category: "Implementation",
    tags: ["Timeline", "Milestones", "Project Management"],
    createdAt: "2025-01-12",
    updatedAt: "2025-02-05",
    isRequired: true,
  },
  {
    id: "q-10",
    text: "How will the requested funding be allocated across different cost categories?",
    relatedProjects: [
      "EU Green Innovation Fund",
      "Horizon Europe Research Grant",
      "Digital Europe Programme",
      "SME Growth Initiative",
    ],
    category: "Financial",
    tags: ["Budget", "Cost Allocation", "Funding"],
    createdAt: "2025-01-15",
    updatedAt: "2025-02-08",
    isRequired: true,
  },
  {
    id: "q-11",
    text: "What is your intellectual property strategy?",
    relatedProjects: ["Horizon Europe Research Grant", "Health Innovation Programme"],
    category: "Technical",
    tags: ["IP", "Patents", "Protection"],
    createdAt: "2025-01-18",
    updatedAt: "2025-02-10",
    isRequired: false,
  },
  {
    id: "q-12",
    text: "How does your team's expertise align with the project requirements?",
    relatedProjects: ["Horizon Europe Research Grant", "Health Innovation Programme"],
    category: "Implementation",
    tags: ["Team", "Expertise", "Capabilities"],
    createdAt: "2025-01-20",
    updatedAt: "2025-02-12",
    isRequired: false,
  },
  {
    id: "q-13",
    text: "What are your plans for scaling the solution after the initial funding period?",
    relatedProjects: ["SME Growth Initiative", "Digital Europe Programme"],
    category: "Implementation",
    tags: ["Scaling", "Growth", "Sustainability"],
    createdAt: "2025-01-22",
    updatedAt: "2025-02-15",
    isRequired: false,
  },
  {
    id: "q-14",
    text: "How will you ensure compliance with relevant regulations and standards?",
    relatedProjects: ["EU Green Innovation Fund", "Health Innovation Programme"],
    category: "Technical",
    tags: ["Compliance", "Regulations", "Standards"],
    createdAt: "2025-01-25",
    updatedAt: "2025-02-18",
    isRequired: true,
  },
  {
    id: "q-15",
    text: "What is your break-even analysis and when do you expect to reach profitability?",
    relatedProjects: ["SME Growth Initiative", "Digital Europe Programme"],
    category: "Financial",
    tags: ["Break-even", "Profitability", "Financial Projection"],
    createdAt: "2025-01-28",
    updatedAt: "2025-02-20",
    isRequired: false,
  },
]
