export interface ApprovedProject {
  id: string
  companyId: string
  companyName: string
  projectId: string
  projectName: string
  approvedById: string
  approvedByName: string
  approvalDate: string
  consultantId: string
  consultantName: string
  status: "ready_to_submit"
  lastUpdated: string
}

export const approvedProjectsData: ApprovedProject[] = [
  {
    id: "app-1",
    companyId: "comp-1",
    companyName: "EcoTech Solutions",
    projectId: "proj-2",
    projectName: "Sustainable Innovation Grant",
    approvedById: "admin-1",
    approvedByName: "Michael Brown",
    approvalDate: "2024-04-12",
    consultantId: "user-1",
    consultantName: "John Doe",
    status: "ready_to_submit",
    lastUpdated: "2024-04-12",
  },
  {
    id: "app-2",
    companyId: "comp-2",
    companyName: "BioMed Research",
    projectId: "proj-4",
    projectName: "Medical Technology Fund",
    approvedById: "admin-2",
    approvedByName: "Lisa Martinez",
    approvalDate: "2024-04-08",
    consultantId: "user-2",
    consultantName: "Sarah Johnson",
    status: "ready_to_submit",
    lastUpdated: "2024-04-08",
  },
  {
    id: "app-3",
    companyId: "comp-3",
    companyName: "AgriTech Innovations",
    projectId: "proj-6",
    projectName: "Agricultural Development Program",
    approvedById: "admin-3",
    approvedByName: "Daniel Lee",
    approvalDate: "2024-04-05",
    consultantId: "user-3",
    consultantName: "Emily Chen",
    status: "ready_to_submit",
    lastUpdated: "2024-04-05",
  },
  {
    id: "app-4",
    companyId: "comp-4",
    companyName: "QuantumTech",
    projectId: "proj-8",
    projectName: "Quantum Computing Research Grant",
    approvedById: "admin-1",
    approvedByName: "Michael Brown",
    approvalDate: "2024-04-02",
    consultantId: "user-4",
    consultantName: "David Wilson",
    status: "ready_to_submit",
    lastUpdated: "2024-04-02",
  },
  {
    id: "app-5",
    companyId: "comp-5",
    companyName: "Urban Mobility Solutions",
    projectId: "proj-10",
    projectName: "Urban Transportation Innovation Fund",
    approvedById: "admin-2",
    approvedByName: "Lisa Martinez",
    approvalDate: "2024-03-30",
    consultantId: "user-5",
    consultantName: "Robert Taylor",
    status: "ready_to_submit",
    lastUpdated: "2024-03-30",
  },
  {
    id: "app-6",
    companyId: "comp-6",
    companyName: "CleanWater Tech",
    projectId: "proj-12",
    projectName: "Water Purification Research Grant",
    approvedById: "admin-3",
    approvedByName: "Daniel Lee",
    approvalDate: "2024-03-28",
    consultantId: "user-6",
    consultantName: "Amanda Lewis",
    status: "ready_to_submit",
    lastUpdated: "2024-03-28",
  },
  {
    id: "app-7",
    companyId: "comp-7",
    companyName: "HealthTech Innovations",
    projectId: "proj-16",
    projectName: "Digital Health Innovation Fund",
    approvedById: "admin-1",
    approvedByName: "Michael Brown",
    approvalDate: "2024-03-25",
    consultantId: "user-7",
    consultantName: "James Wilson",
    status: "ready_to_submit",
    lastUpdated: "2024-03-25",
  },
  {
    id: "app-8",
    companyId: "comp-8",
    companyName: "RenewEnergy Corp",
    projectId: "proj-19",
    projectName: "Renewable Energy Development Grant",
    approvedById: "admin-2",
    approvedByName: "Lisa Martinez",
    approvalDate: "2024-03-22",
    consultantId: "user-8",
    consultantName: "Sophia Garcia",
    status: "ready_to_submit",
    lastUpdated: "2024-03-22",
  },
  {
    id: "app-9",
    companyId: "comp-9",
    companyName: "SmartFarm Systems",
    projectId: "proj-22",
    projectName: "Smart Agriculture Fund",
    approvedById: "admin-3",
    approvedByName: "Daniel Lee",
    approvalDate: "2024-03-20",
    consultantId: "user-9",
    consultantName: "Olivia Thompson",
    status: "ready_to_submit",
    lastUpdated: "2024-03-20",
  },
  {
    id: "app-10",
    companyId: "comp-10",
    companyName: "NanoTech Solutions",
    projectId: "proj-25",
    projectName: "Nanotechnology Research Program",
    approvedById: "admin-1",
    approvedByName: "Michael Brown",
    approvalDate: "2024-03-18",
    consultantId: "user-10",
    consultantName: "William Clark",
    status: "ready_to_submit",
    lastUpdated: "2024-03-18",
  },
]
