export const dashboardData = {
  kpis: {
    totalProjects: 124,
    totalCompanies: 47,
    successRate: 78,
    totalAnalyses: 312,
    totalApplicationsSubmitted: 96,
    activeApplications: 28,
    completedProjects: 68,
    upcomingDeadlines: 12,
  },
  recentProjects: [
    {
      id: "proj-1",
      title: "EU Green Innovation Fund",
      deadline: "2025-06-15",
      fundingAmount: 750000,
      sector: "Sustainability",
      status: "active",
    },
    {
      id: "proj-2",
      title: "Horizon Europe Research Grant",
      deadline: "2025-04-22",
      fundingAmount: 1250000,
      sector: "Research",
      status: "pending",
    },
    {
      id: "proj-3",
      title: "Digital Europe Programme",
      deadline: "2025-05-10",
      fundingAmount: 500000,
      sector: "Technology",
      status: "active",
    },
    {
      id: "proj-4",
      title: "SME Growth Initiative",
      deadline: "2025-03-05",
      fundingAmount: 350000,
      sector: "Business",
      status: "completed",
    },
    {
      id: "proj-5",
      title: "Creative Europe Media",
      deadline: "2025-07-18",
      fundingAmount: 420000,
      sector: "Media",
      status: "pending",
    },
  ],
  recentCompanies: [
    {
      id: "comp-1",
      name: "EcoTech Solutions",
      sector: "Clean Energy",
      contactPerson: {
        name: "Maria Rodriguez",
        email: "maria@ecotech.com",
      },
      projectCount: 3,
    },
    {
      id: "comp-2",
      name: "MediNova Research",
      sector: "Healthcare",
      contactPerson: {
        name: "Thomas Weber",
        email: "t.weber@medinova.com",
      },
      projectCount: 2,
    },
    {
      id: "comp-3",
      name: "DigitalMind AI",
      sector: "Technology",
      contactPerson: {
        name: "Sarah Chen",
        email: "sarah@digitalmind.ai",
      },
      projectCount: 4,
    },
    {
      id: "comp-4",
      name: "GreenGrow Agriculture",
      sector: "Agriculture",
      contactPerson: {
        name: "John Peterson",
        email: "j.peterson@greengrow.com",
      },
      projectCount: 1,
    },
    {
      id: "comp-5",
      name: "Urban Mobility Solutions",
      sector: "Transportation",
      contactPerson: {
        name: "Elena Kowalski",
        email: "elena@urbanmobility.com",
      },
      projectCount: 2,
    },
  ],
  recentSubmissions: [
    {
      id: "sub-1",
      projectTitle: "EU Green Innovation Fund",
      companyName: "EcoTech Solutions",
      submissionDate: "2025-02-10",
      status: "Under Review",
      fundingAmount: 750000,
    },
    {
      id: "sub-2",
      projectTitle: "Horizon Europe Research Grant",
      companyName: "MediNova Research",
      submissionDate: "2025-02-05",
      status: "Submitted",
      fundingAmount: 1250000,
    },
    {
      id: "sub-3",
      projectTitle: "Digital Europe Programme",
      companyName: "DigitalMind AI",
      submissionDate: "2025-01-28",
      status: "Under Review",
      fundingAmount: 500000,
    },
    {
      id: "sub-4",
      projectTitle: "SME Growth Initiative",
      companyName: "GreenGrow Agriculture",
      submissionDate: "2025-01-15",
      status: "Approved",
      fundingAmount: 350000,
    },
  ],
  projectsAwaitingAction: [
    {
      id: "await-1",
      projectTitle: "Renewable Energy Grant",
      companyName: "EcoTech Solutions",
      deadline: "2025-10-10",
      status: "Awaiting AI Writing",
      progress: 35,
      sectionsCompleted: 3,
      totalSections: 8,
    },
    {
      id: "await-2",
      projectTitle: "Health Innovation Programme",
      companyName: "MediNova Research",
      deadline: "2025-08-30",
      status: "Under Review",
      progress: 75,
      sectionsCompleted: 6,
      totalSections: 8,
    },
    {
      id: "await-3",
      projectTitle: "AI Development Grant",
      companyName: "DigitalMind AI",
      deadline: "2025-06-30",
      status: "Awaiting AI Writing",
      progress: 25,
      sectionsCompleted: 2,
      totalSections: 8,
    },
    {
      id: "await-4",
      projectTitle: "Agricultural Innovation Fund",
      companyName: "GreenGrow Agriculture",
      deadline: "2025-05-28",
      status: "Under Review",
      progress: 90,
      sectionsCompleted: 7,
      totalSections: 8,
    },
    {
      id: "await-5",
      projectTitle: "Urban Innovation Initiative",
      companyName: "Urban Mobility Solutions",
      deadline: "2025-07-25",
      status: "Awaiting AI Writing",
      progress: 50,
      sectionsCompleted: 4,
      totalSections: 8,
    },
  ],
  upcomingDeadlines: [
    {
      id: "deadline-1",
      projectTitle: "SME Growth Initiative",
      companyName: "Urban Mobility Solutions",
      deadline: "2025-03-05",
      daysRemaining: 12,
      progress: 85,
    },
    {
      id: "deadline-2",
      projectTitle: "Horizon Europe Research Grant",
      companyName: "EcoTech Solutions",
      deadline: "2025-03-10",
      daysRemaining: 17,
      progress: 60,
    },
    {
      id: "deadline-3",
      projectTitle: "Digital Europe Programme",
      companyName: "DigitalMind AI",
      deadline: "2025-03-15",
      daysRemaining: 22,
      progress: 45,
    },
  ],
}
