export interface DocumentSection {
  id: string
  title: string
  description: string
  associatedProjects: string[]
  wordCountMin?: number
  wordCountMax?: number
  isRequired: boolean
  order: number
  createdAt: string
  updatedAt: string
  category: "Overview" | "Technical" | "Financial" | "Impact" | "Implementation"
}

export const documentSectionsData: DocumentSection[] = [
  {
    id: "section-1",
    title: "Executive Summary",
    description: "Brief overview of the project, its objectives, and expected outcomes",
    associatedProjects: ["EU Green Innovation Fund", "Horizon Europe Research Grant", "SME Growth Initiative"],
    wordCountMin: 200,
    wordCountMax: 300,
    isRequired: true,
    order: 1,
    createdAt: "2024-11-15",
    updatedAt: "2025-01-10",
    category: "Overview",
  },
  {
    id: "section-2",
    title: "Problem Statement",
    description: "Clear definition of the problem being addressed",
    associatedProjects: ["EU Green Innovation Fund", "Horizon Europe Research Grant", "Digital Europe Programme"],
    wordCountMin: 150,
    wordCountMax: 250,
    isRequired: true,
    order: 2,
    createdAt: "2024-11-15",
    updatedAt: "2025-01-10",
    category: "Overview",
  },
  {
    id: "section-3",
    title: "Proposed Solution",
    description: "Detailed description of the innovative solution",
    associatedProjects: ["EU Green Innovation Fund", "Horizon Europe Research Grant", "Digital Europe Programme"],
    wordCountMin: 300,
    wordCountMax: 500,
    isRequired: true,
    order: 3,
    createdAt: "2024-11-15",
    updatedAt: "2025-01-12",
    category: "Technical",
  },
  {
    id: "section-4",
    title: "Innovation Aspects",
    description: "Explanation of what makes the solution innovative",
    associatedProjects: ["EU Green Innovation Fund", "Horizon Europe Research Grant", "Digital Europe Programme"],
    wordCountMin: 250,
    wordCountMax: 400,
    isRequired: true,
    order: 4,
    createdAt: "2024-11-15",
    updatedAt: "2025-01-15",
    category: "Technical",
  },
  {
    id: "section-5",
    title: "Environmental Impact",
    description: "Assessment of the environmental benefits",
    associatedProjects: ["EU Green Innovation Fund", "Circular Economy Fund", "Renewable Energy Grant"],
    wordCountMin: 300,
    wordCountMax: 500,
    isRequired: true,
    order: 5,
    createdAt: "2024-11-18",
    updatedAt: "2025-01-20",
    category: "Impact",
  },
  {
    id: "section-6",
    title: "Market Analysis",
    description: "Overview of the target market and competition",
    associatedProjects: [
      "SME Growth Initiative",
      "Digital Europe Programme",
      "Health Innovation Programme",
      "AI Development Grant",
    ],
    wordCountMin: 400,
    wordCountMax: 600,
    isRequired: true,
    order: 6,
    createdAt: "2024-11-20",
    updatedAt: "2025-01-22",
    category: "Financial",
  },
  {
    id: "section-7",
    title: "Implementation Plan",
    description: "Detailed plan for project implementation",
    associatedProjects: [
      "EU Green Innovation Fund",
      "Horizon Europe Research Grant",
      "Digital Europe Programme",
      "SME Growth Initiative",
    ],
    wordCountMin: 400,
    wordCountMax: 700,
    isRequired: true,
    order: 7,
    createdAt: "2024-11-22",
    updatedAt: "2025-01-25",
    category: "Implementation",
  },
  {
    id: "section-8",
    title: "Budget & Financial Plan",
    description: "Detailed budget breakdown and financial projections",
    associatedProjects: [
      "EU Green Innovation Fund",
      "Horizon Europe Research Grant",
      "Digital Europe Programme",
      "SME Growth Initiative",
    ],
    wordCountMin: 300,
    wordCountMax: 500,
    isRequired: true,
    order: 8,
    createdAt: "2024-11-25",
    updatedAt: "2025-01-28",
    category: "Financial",
  },
  {
    id: "section-9",
    title: "Team & Expertise",
    description: "Information about the team and their qualifications",
    associatedProjects: ["Horizon Europe Research Grant", "Health Innovation Programme"],
    wordCountMin: 200,
    wordCountMax: 400,
    isRequired: false,
    order: 9,
    createdAt: "2024-11-28",
    updatedAt: "2025-01-30",
    category: "Implementation",
  },
  {
    id: "section-10",
    title: "Risk Assessment",
    description: "Identification of potential risks and mitigation strategies",
    associatedProjects: ["EU Green Innovation Fund", "Horizon Europe Research Grant", "Health Innovation Programme"],
    wordCountMin: 250,
    wordCountMax: 400,
    isRequired: true,
    order: 10,
    createdAt: "2024-12-01",
    updatedAt: "2025-02-01",
    category: "Implementation",
  },
  {
    id: "section-11",
    title: "Sustainability Plan",
    description: "Plan for ensuring project sustainability beyond the funding period",
    associatedProjects: ["EU Green Innovation Fund", "Circular Economy Fund", "Renewable Energy Grant"],
    wordCountMin: 200,
    wordCountMax: 350,
    isRequired: false,
    order: 11,
    createdAt: "2024-12-05",
    updatedAt: "2025-02-05",
    category: "Impact",
  },
  {
    id: "section-12",
    title: "Dissemination Strategy",
    description: "Plan for sharing project results and knowledge",
    associatedProjects: ["Horizon Europe Research Grant", "Digital Europe Programme"],
    wordCountMin: 200,
    wordCountMax: 350,
    isRequired: false,
    order: 12,
    createdAt: "2024-12-08",
    updatedAt: "2025-02-08",
    category: "Implementation",
  },
  {
    id: "section-13",
    title: "Policy Alignment",
    description: "Explanation of how the project aligns with relevant policies",
    associatedProjects: ["EU Green Innovation Fund", "Circular Economy Fund"],
    wordCountMin: 150,
    wordCountMax: 300,
    isRequired: false,
    order: 13,
    createdAt: "2024-12-10",
    updatedAt: "2025-02-10",
    category: "Impact",
  },
  {
    id: "section-14",
    title: "Intellectual Property Strategy",
    description: "Strategy for managing intellectual property",
    associatedProjects: ["Horizon Europe Research Grant", "Health Innovation Programme", "AI Development Grant"],
    wordCountMin: 150,
    wordCountMax: 300,
    isRequired: false,
    order: 14,
    createdAt: "2024-12-12",
    updatedAt: "2025-02-12",
    category: "Technical",
  },
  {
    id: "section-15",
    title: "Monitoring & Evaluation Framework",
    description: "Framework for monitoring project progress and evaluating outcomes",
    associatedProjects: ["EU Green Innovation Fund", "Horizon Europe Research Grant"],
    wordCountMin: 200,
    wordCountMax: 350,
    isRequired: false,
    order: 15,
    createdAt: "2024-12-15",
    updatedAt: "2025-02-15",
    category: "Implementation",
  },
]
