export interface InReviewProject {
  id: string
  companyId: string
  companyName: string
  projectId: string
  projectName: string
  consultantId: string
  consultantName: string
  completionDate: string
  reviewStatus: "awaiting_review" | "under_review"
  assignedAdminId?: string
  assignedAdminName?: string
  lastUpdated: string
}

export const inReviewProjectsData: InReviewProject[] = [
  {
    id: "rev-1",
    companyId: "comp-1",
    companyName: "EcoTech Solutions",
    projectId: "proj-1",
    projectName: "EU Green Innovation Fund",
    consultantId: "user-1",
    consultantName: "John Doe",
    completionDate: "2024-04-15",
    reviewStatus: "awaiting_review",
    lastUpdated: "2024-04-15",
  },
  {
    id: "rev-2",
    companyId: "comp-2",
    companyName: "BioMed Research",
    projectId: "proj-3",
    projectName: "Horizon Europe Health Grant",
    consultantId: "user-2",
    consultantName: "Sarah Johnson",
    completionDate: "2024-04-10",
    reviewStatus: "under_review",
    assignedAdminId: "admin-1",
    assignedAdminName: "Michael Brown",
    lastUpdated: "2024-04-12",
  },
  {
    id: "rev-3",
    companyId: "comp-3",
    companyName: "AgriTech Innovations",
    projectId: "proj-5",
    projectName: "Rural Development Fund",
    consultantId: "user-3",
    consultantName: "Emily Chen",
    completionDate: "2024-04-08",
    reviewStatus: "awaiting_review",
    lastUpdated: "2024-04-08",
  },
  {
    id: "rev-4",
    companyId: "comp-4",
    companyName: "QuantumTech",
    projectId: "proj-7",
    projectName: "Digital Innovation Fund",
    consultantId: "user-4",
    consultantName: "David Wilson",
    completionDate: "2024-04-05",
    reviewStatus: "under_review",
    assignedAdminId: "admin-2",
    assignedAdminName: "Lisa Martinez",
    lastUpdated: "2024-04-07",
  },
  {
    id: "rev-5",
    companyId: "comp-5",
    companyName: "Urban Mobility Solutions",
    projectId: "proj-9",
    projectName: "Smart Cities Grant",
    consultantId: "user-5",
    consultantName: "Robert Taylor",
    completionDate: "2024-04-03",
    reviewStatus: "awaiting_review",
    lastUpdated: "2024-04-03",
  },
  {
    id: "rev-6",
    companyId: "comp-6",
    companyName: "CleanWater Tech",
    projectId: "proj-11",
    projectName: "Environmental Protection Fund",
    consultantId: "user-6",
    consultantName: "Amanda Lewis",
    completionDate: "2024-04-01",
    reviewStatus: "under_review",
    assignedAdminId: "admin-1",
    assignedAdminName: "Michael Brown",
    lastUpdated: "2024-04-02",
  },
  {
    id: "rev-7",
    companyId: "comp-7",
    companyName: "HealthTech Innovations",
    projectId: "proj-15",
    projectName: "Medical Research Grant",
    consultantId: "user-7",
    consultantName: "James Wilson",
    completionDate: "2024-03-28",
    reviewStatus: "awaiting_review",
    lastUpdated: "2024-03-28",
  },
  {
    id: "rev-8",
    companyId: "comp-8",
    companyName: "RenewEnergy Corp",
    projectId: "proj-18",
    projectName: "Sustainable Energy Fund",
    consultantId: "user-8",
    consultantName: "Sophia Garcia",
    completionDate: "2024-03-25",
    reviewStatus: "under_review",
    assignedAdminId: "admin-3",
    assignedAdminName: "Daniel Lee",
    lastUpdated: "2024-03-27",
  },
  {
    id: "rev-9",
    companyId: "comp-9",
    companyName: "SmartFarm Systems",
    projectId: "proj-21",
    projectName: "Agricultural Innovation Grant",
    consultantId: "user-9",
    consultantName: "Olivia Thompson",
    completionDate: "2024-03-22",
    reviewStatus: "awaiting_review",
    lastUpdated: "2024-03-22",
  },
  {
    id: "rev-10",
    companyId: "comp-10",
    companyName: "NanoTech Solutions",
    projectId: "proj-24",
    projectName: "Advanced Materials Research Fund",
    consultantId: "user-10",
    consultantName: "William Clark",
    completionDate: "2024-03-20",
    reviewStatus: "under_review",
    assignedAdminId: "admin-2",
    assignedAdminName: "Lisa Martinez",
    lastUpdated: "2024-03-21",
  },
  {
    id: "rev-11",
    companyId: "comp-1",
    companyName: "EcoTech Solutions",
    projectId: "proj-12",
    projectName: "Climate Action Grant",
    consultantId: "user-1",
    consultantName: "John Doe",
    completionDate: "2024-03-18",
    reviewStatus: "awaiting_review",
    lastUpdated: "2024-03-18",
  },
  {
    id: "rev-12",
    companyId: "comp-2",
    companyName: "BioMed Research",
    projectId: "proj-25",
    projectName: "Healthcare Innovation Program",
    consultantId: "user-2",
    consultantName: "Sarah Johnson",
    completionDate: "2024-03-15",
    reviewStatus: "under_review",
    assignedAdminId: "admin-3",
    assignedAdminName: "Daniel Lee",
    lastUpdated: "2024-03-17",
  },
]
