export interface SubmittedProject {
  id: string
  companyId: string
  companyName: string
  projectId: string
  projectName: string
  submissionDate: string
  submittedById: string
  submittedByName: string
  status: "awaiting_result" | "approved" | "rejected"
  lastUpdated: string
  notes?: string
}

export const submittedProjectsData: SubmittedProject[] = [
  {
    id: "sub-1",
    companyId: "comp-1",
    companyName: "EcoTech Solutions",
    projectId: "proj-1",
    projectName: "EU Green Innovation Fund",
    submissionDate: "2024-03-15",
    submittedById: "user-1",
    submittedByName: "John Doe",
    status: "awaiting_result",
    lastUpdated: "2024-03-15",
    notes: "Application submitted after final review by the board.",
  },
  {
    id: "sub-2",
    companyId: "comp-2",
    companyName: "BioMed Research",
    projectId: "proj-3",
    projectName: "Horizon Europe Health Grant",
    submissionDate: "2024-02-28",
    submittedById: "user-2",
    submittedByName: "Sarah Johnson",
    status: "approved",
    lastUpdated: "2024-04-10",
    notes: "Approved with full funding amount. Project to start in June 2024.",
  },
  {
    id: "sub-3",
    companyId: "comp-3",
    companyName: "AgriTech Innovations",
    projectId: "proj-5",
    projectName: "Rural Development Fund",
    submissionDate: "2024-01-20",
    submittedById: "user-3",
    submittedByName: "Michael Brown",
    status: "rejected",
    lastUpdated: "2024-03-05",
    notes: "Rejected due to budget constraints. Recommended to reapply in next cycle with revised scope.",
  },
  {
    id: "sub-4",
    companyId: "comp-4",
    companyName: "QuantumTech",
    projectId: "proj-7",
    projectName: "Digital Innovation Fund",
    submissionDate: "2024-03-01",
    submittedById: "user-1",
    submittedByName: "John Doe",
    status: "awaiting_result",
    lastUpdated: "2024-03-01",
    notes: "Application submitted with all supporting documents.",
  },
  {
    id: "sub-5",
    companyId: "comp-5",
    companyName: "Urban Mobility Solutions",
    projectId: "proj-9",
    projectName: "Smart Cities Grant",
    submissionDate: "2024-02-15",
    submittedById: "user-4",
    submittedByName: "Emily Chen",
    status: "approved",
    lastUpdated: "2024-04-05",
    notes: "Approved with 85% of requested funding. Need to revise budget accordingly.",
  },
  {
    id: "sub-6",
    companyId: "comp-6",
    companyName: "CleanWater Tech",
    projectId: "proj-11",
    projectName: "Environmental Protection Fund",
    submissionDate: "2024-01-10",
    submittedById: "user-5",
    submittedByName: "David Wilson",
    status: "rejected",
    lastUpdated: "2024-02-28",
    notes: "Rejected due to incomplete technical documentation. Feedback provided for future applications.",
  },
  {
    id: "sub-7",
    companyId: "comp-1",
    companyName: "EcoTech Solutions",
    projectId: "proj-12",
    projectName: "Climate Action Grant",
    submissionDate: "2024-03-20",
    submittedById: "user-1",
    submittedByName: "John Doe",
    status: "awaiting_result",
    lastUpdated: "2024-03-20",
    notes: "Application submitted after addressing all reviewer comments.",
  },
  {
    id: "sub-8",
    companyId: "comp-7",
    companyName: "HealthTech Innovations",
    projectId: "proj-15",
    projectName: "Medical Research Grant",
    submissionDate: "2024-02-05",
    submittedById: "user-6",
    submittedByName: "Lisa Martinez",
    status: "approved",
    lastUpdated: "2024-03-25",
    notes: "Approved with full funding. Project kickoff scheduled for May 2024.",
  },
  {
    id: "sub-9",
    companyId: "comp-8",
    companyName: "RenewEnergy Corp",
    projectId: "proj-18",
    projectName: "Sustainable Energy Fund",
    submissionDate: "2024-01-25",
    submittedById: "user-7",
    submittedByName: "Robert Taylor",
    status: "awaiting_result",
    lastUpdated: "2024-01-25",
    notes: "Application submitted. Awaiting initial review.",
  },
  {
    id: "sub-10",
    companyId: "comp-9",
    companyName: "SmartFarm Systems",
    projectId: "proj-21",
    projectName: "Agricultural Innovation Grant",
    submissionDate: "2024-02-18",
    submittedById: "user-8",
    submittedByName: "Amanda Lewis",
    status: "rejected",
    lastUpdated: "2024-04-01",
    notes:
      "Rejected due to similar projects already funded. Suggested to focus on different aspects of agricultural technology.",
  },
]
